### ISSUE TITLE
Code becomes outdated, missing automation

### ISSUE THREAD

**Issue by AndreyDodonov-EH** [twa-dev/SDK#16]
Hi,

I see the package is slightly outdated.

if I create a PR with a Github action which updates the code once the new version of SDK is released,
would such a PR be welcome?

Ideally, we could also add npm publishing leveraging Github Secrets.

Best Regards
Andrey

**Comment by nexus6nexus6** [comment]
Hi there @ArthurStam 
We're also interested in updating the code .. we're missing the latest `isVerticalSwipesEnabled` that they have in v7.7 .. but love to keep this package as our dep and not go directly with their script.
Thank you so much!

**Comment by gregmeszaros** [comment]
@nexus6nexus6 created the issue here https://github.com/twa-dev/SDK/issues/19 also missing that isVerticalSwipesEnabled function

**Comment by ArthurStam** [comment]
Done
