### ISSUE TITLE
Bump from Bot API 7.0 to Bot API 7.7

### ISSUE THREAD

**Issue by gregmeszaros** [twa-dev/SDK#19]
Any plans to support the latest versions of the telegram-web-app.js?

Recent changes

July 7, 2024
Bot API 7.7

Added the field isVerticalSwipesEnabled and the methods enableVerticalSwipes, disableVerticalSwipes to the class [WebApp](https://core.telegram.org/bots/webapps#initializing-mini-apps).

Especially i am looking at this which was added recently to disableVerticalSwipes which is a big UI improvement, but looks like it's unsupported within your SDK at the moment.

**Comment by mikiyasET** [comment]
I started using [another package](https://www.npmjs.com/package/telegram-mini-app) since this one is out of date

**Comment by ArthurStam** [comment]
Done. Sorry for the delay.
