### ISSUE TITLE
Incorrect chat_instance in WebApp.initDataUnsafe after update

### ISSUE THREAD

**Issue by Serdar17** [twa-dev/SDK#20]
Hi,
after updating to version 7.8.0, the chat_instance field of the InitDataUsafe object returns a different id on different devices (the expected behavior before version 7.8.0 was always the only one unique for different devices). Can you explain is this a bug with your sdk or is there a problem on the Telegram side?

Example:
![image](https://github.com/user-attachments/assets/19a7b70d-0b03-4124-819b-6ecf1c706690)

twa-dev/sdk: 7.8.0
React: 18.2.0
Telegram Android: 15.10.0

**Comment by ArthurStam** [comment]
I guess it's on Telegram side. I have never worked with `chat_instance` prop, but I can assure you that our wrapper does nothing with this prop. We just export what Telegram SDK returns.

**Comment by Serdar17** [comment]
yes, this is a bug on the telegram side. more [here](https://bugs.telegram.org/c/42737)

**Comment by Serdar17** [comment]
yes, this is a bug on the telegram side. more [here](https://bugs.telegram.org/c/42737)
