### ISSUE TITLE
ReferenceError: window is not defined on node js

### ISSUE THREAD

**Issue by young-tea** [twa-dev/SDK#22]
Just started using the @twa-dev/sdk, and the first thing I see when tyring to test is 

ReferenceError: window is not defined

so the error is not on my side, it points out the node_modules/@twa-dev/sdk/dist/telegram-web-apps.js:248:5

Any fixes? Or maybe I am doing something wrong? Using const WebApp = require('@twa-dev/sdk'), and there is no code based on it

**Comment by n8m** [comment]
Facing the same issue on client side with React

**Comment by ZETECdev** [comment]
same here

**Comment by ArthurStam** [comment]
This library won't work on server side, sorry.

**Comment by ZETECdev** [comment]
yes, the problem is caused by next js , nees use from client
