### ISSUE TITLE
Faced with the problem of using WebApp.theme parameters.text_color('fff'). 

### ISSUE THREAD

**Issue by Roman-00** [twa-dev/SDK#26]
Faced with the problem of using WebApp.theme parameters.text_color('fff'). Outputs the following information: _ twa_dev_sdk__WEBPACK_IMPORTED_MODULE _4__.default theme settings.text_color is not a function

```code
React.useEffect(() => {
        if (typeof window !== 'undefined') {
            WebApp.setHeaderColor('#38c1ff');

            WebApp.themeParams.text_color('fff');
        }
    }, []);
```

![img-exaple](https://github.com/user-attachments/assets/e1528168-c993-4f13-b18b-9c43118a2eb6)

I wanted to change the color in the native header

NextJS v14 TS

**Comment by ArthurStam** [comment]
You can't change text color inside the header. The only thing you can control is the background. AFAIK, Telegram adapts color of the text inside header itself. `WebApp.themeParams` is read-only.

**Comment by Roman-00** [comment]
> ou can't change text color inside the header. The only thing you can control is the background. AFAIK, Telegram adapts color of the text inside header itself. `WebApp.themeParams` is read-only.

Thanks a lot
