### ISSUE TITLE
BotAPI - 8.0

### ISSUE THREAD

**Issue by LordSkare** [twa-dev/SDK#32]
Telegram has released a new major update of BotAPI - 8.0

https://telegram.org/blog/fullscreen-miniapps-and-more/

Tell me, will new methods like requestFullscreen and addToHomeScreen be available in this SDK?
Or haven't had time to update the repository yet?

**Comment by ArthurStam** [comment]
I will update this package as soon as [MR with types](https://github.com/twa-dev/types/pull/10) is merged and types package is updated

**Comment by ArthurStam** [comment]
It's done https://github.com/twa-dev/SDK/releases/tag/v8.0.1
