### ISSUE TITLE
Add support for bot API 8.0

### ISSUE THREAD

**Issue by SethuXD** [twa-dev/SDK#36]
Telegram just dropped Bot API 8.0
 https://core.telegram.org/bots/api-changelog#november-17-2024.

Can you update the SDK to support the new API version? 

Thanks!

**Comment by jaavid** [comment]
@openhands-agent can you fix it ?

**Comment by ennucore** [comment]
Is there a workaround until it's updated? There's a [pull request](https://github.com/twa-dev/SDK/pull/34), maybe one can use that version it the meantime, but I haven't been able to make it work

**Comment by ArthurStam** [comment]
Duplicate of #32
